var Config = Config || {};

Config.bannedHosts = ['cool.jit.su', 'pokeball-nixonserver.rhcloud.com', /\.glitch\.me/];
//Config.afd = true;
Config.whitelist = [
	// general sites
	'wikipedia.org',
	'wikimedia.org',
	'wiktionary.org',
	'github.com',
	'reddit.com',
	'gamefaqs.com',
	'facebook.com',
	'fbcdn.net',
	'twitter.com',
	'tumblr.com',
	'deviantart.com',
	'youtube.com',
	'youtu.be',
	'zombo.com',
	'strawpoll.me',
	'twitch.tv',
	'take-a-screenshot.org',
	'4chan.org',
	'tumblr.com',
	'git.io',
	'mibbit.com',
	'codecademy.com',
	'xkcd.com',
	'stackoverflow.com',
	'stackexchange.com',
	'malwarebytes.org',
	'zombo.com',
	'html5zombo.com',
	'whatismyipaddress.com',
	'iplocationtools.com',
	'iplocation.net',
	'ipqualityscore.com',

	// pokemon sites
	'pokemonshowdown.com',
	'psim.us',
	'smogon.com',
	'upokecenter.com',
	'veekun.com',
	'bulbagarden.net',
	'serebii.net',
	'nuggetbridge.com',
	'pokecommunity.com',
	'pokemon-online.eu',
	'pokemonlab.com',
	'shoddybattle.com',
	'pokemonxy.com',
	'pokemon.com',
	'pokemon-gl.com',
	'pokecheck.org',
	'projectpokemon.org',
	'pokemondb.net',
	'pokemoncentral.it',
	'poketrade.us',
	'neverused.net',
	'pokestrat.com',
	'pokestrat.io',
	'spo.ink',
	'jooas.com',
	'pokemongodb.net',
	'pokeassistant.com',
	'pokemon-sunmoon.com',
	'gamepress.gg',
	'trainertower.com',
	'pokepast.es',
	'pokepedia.fr',
	'randbatscalc.github.io',
	'ruins-of-alph.github.io',
	'gamespot.com',
	'victoryroadvgc.com',
	'pikalytics.com',
	'vgcstats.com',
	'worldcupvgc.com',

	// personal sites
	'breakdown.forumotion.com',
	'pokemonmillennium.net',
	'thebattletower.no-ip.org',
	'meltsner.com',
	'guangcongluo.com',
	'cathyjf.com',
	'xiaotai.org',
	'xfix.pw',
	'pkmn.cc',
	'strategydatabase.jimdo.com',
	'hidden50.github.io',
	'krisxv.github.io',
	'psbot.xyz',
	'pswifi.github.io',
	// personal hosting sites
	'forumieren.com',
	'soforums.com',
	'proboards.com',
	'weebly.com',
	'freeforums.org',
	'forumactif.com',
	'forumotion.com',
	'bigbangpokemon.com',
	'sites.google.com',

	// rich text
	'docs.google.com',

	// text
	'pastebin.com',
	'hastebin.com',
	'pastie.io',
	'trello.com',
	'challonge.com',
	'piratepad.net',
	'pastebin.run',

	// anime
	'myanimelist.net',
	'animenewsnetwork.com',
	'animenewsnetwork.cc',
	'anilist.co',
	'mangaupdates.com',
	'anime-planet.com',
	'anichart.net',

	// music
	'plug.dj',
	'openings.moe',
    'animethemes.moe',
	'catbox.moe',

	// images
	'prntscr.com',
	'prnt.sc',
	'puu.sh',
	'd.pr',
	'snag.gy',
	'gyazo.com',
	'imgur.com',
	'gfycat.com',
	'4cdn.org',
	'discordapp.com'
];

Config.roomsFirstOpenScript = function (mainMenuOnly) {
	/* eslint-disable */
	if (mainMenuOnly) {
		$('.leftmenu .activitymenu').first().after('<div id="div-gpt-ad-pks-7"></div>');
		try {
      egAps.reinstate();
		} catch (e) {}
	// } else if ($(window).width() >= 800) {
	// 	$('.roomlisttop').first().after('<div id="div-gpt-ad-pks-3"></div>');
	// 	$('.roomlist').first().after('<div id="div-gpt-ad-pks-4"></div>');
	// 	try {
  //     egAps.reinstate();
	// 	} catch (e) {}
	} else {
		$('.roomlisttop').first().after('<div style="max-width:480px"><div id="div-gpt-ad-pks-3"></div></div>');
		$('.roomlist').first().after('<div style="max-width:480px"><div id="div-gpt-ad-pks-4"></div></div>');
		try {
      egAps.reinstate();
    } catch (e) {}
	}
	/* eslint-enable */
};

Config.customcolors = {
	'theimmortal': 'taco',
	'bmelts': 'testmelts',
	'jumpluff': 'zacchaeus',
	'zacchaeus': 'jumpluff',
	'kraw': 'kraw1',
	'growlithe': 'steamroll',
	'snowflakes': 'endedinariot',
	'doomvendingmachine': 'theimmortal',
	'mikel': 'mikkel',
	'arcticblast': 'rsem',
	'mjb': 'thefourthchaser',
	'thefourthchaser': 'mjb',
	'tfc': 'mjb',
	'mikedecishere': 'mikedec3boobs',
	'heartsonfire': 'haatsuonfaiyaa',
	'royalty': 'wonder9',
	'limi': 'azure2',
	'ginganinja': 'piratesandninjas',
	'aurora': 'c6n6fek',
	'jdarden': 'danielcross',
	'solace': 'amorlan',
	'dcae': 'galvatron',
	'queenofrandoms': 'hahaqor',
	'jelandee': 'thejelandee',
	'diatom': 'dledledlewhooop',
	'texascloverleaf': 'aggronsmash',
	'treecko': 'treecko56',
	'violatic': 'violatic92',
	'exeggutor': 'ironmanatee',
	'ironmanatee': 'exeggutor',
	'skylight': 'aerithass',
	'nekonay': 'catbot20',
	'coronis': 'kowonis',
	'vaxter': 'anvaxter',
	'mattl': 'mattl34',
	'shaymin': 'test33',
	'kayo': 'endedinariot',
	'tgmd': 'greatmightydoom',
	'vacate': 'vacatetest',
	'bean': 'dragonbean',
	'yunan': 'osiris13',
	'politoed': 'brosb4hoohs',
	'scotteh': 'nsyncluvr67',
	'bumbadadabum': 'styrofoamboots',
	'yuihirasawa': 'weeabookiller',
	'monohearted': 'nighthearted',
	'prem': 'erinanakiri', // second color change
	'clefairy': 'fuckes',
	'morfent': 'aaaa',
	'crobat': 'supergaycrobat4',
	'beowulf': '298789z7z',
	'flippy': 'flippo',
	'raoulsteve247': 'raoulbuildingpc',
	'thedeceiver': 'colourtest011',
	'darnell': 'ggggggg',
	'shamethat': 'qpwkfklkjpskllj', // second color change
	'aipom': 'wdsddsdadas',
	'alter': 'spakling',
	'biggie': 'aoedoedad',
	'osiris': 'osiris12', // second color change
	'azumarill': 'azumarill69',
	'redew': 'redeww',
	'sapphire': 'masquerains',
	'calyxium': 'calyxium142',
	'kiracookie': 'kracookie',
	'blitz': 'hikaruhitachii',
	'skitty': 'shckieei',
	'sweep': 'jgjjfgdfg', // second color change
	'panpawn': 'crowt',
	'val': 'pleasegivemecolorr',
	'valentine': 'pleasegivemecolorr',
	'briayan': 'haxorusxi',
	'xzern': 'mintycolors',
	'shgeldz': 'cactusl00ver',
	'abra': 'lunchawaits',
	'maomiraen': 'aaaaaa',
	'trickster': 'sunako',
	'articuno': 'bluekitteh177',
	'barton': 'hollywood15',
	'zodiax': '5olanto4',
	'ninetynine': 'blackkkk',
	'kasumi': 'scooter4000',
	'xylen': 'bloodyrevengebr',
	'aelita': 'y34co3',
	'fx': 'cm48ubpq',
	'horyzhnz': 'superguy69',
	'quarkz': 'quarkz345',
	'fleurdyleurse': 'calvaryfishes',
	'trinitrotoluene': '4qpr7pc5mb',
	'yuno': 'qgadlu6g',
	'austin': 'jkjkjkjkjkgdl',
	'jinofthegale': 'cainvelasquez',
	'waterbomb': 'naninan',
	'starbloom': 'taigaaisaka',
	'macle': 'flogged',
	'ashiemore': 'poncp',
	'charles': 'charlescarmichael',
	'sigilyph': 'diving', // second color change
	'spy': 'spydreigon',
	'kinguu': 'dodmen',
	'dodmen': 'kinguu',
	'magnemite': 'dsfsdffs',
	'ace': 'sigilyph143',
	'leftiez': 'xxxxnbbhiojll',
	'grim': 'grimoiregod',
	'strength': '0v0tqpnu',
	'honchkrow': 'nsyncluvr67',
	'quote': '64z7i',
	'snow': 'q21yzqgh',
	'omegaxis': 'omegaxis14',
	'paradise': 'rnxvzwpwtz',
	'sailorcosmos': 'goldmedalpas',
	'dontlose': 'dhcli22h',
	'tatsumaki': 'developmentary',
	'starry': 'starryblanket',
	'imas': 'imas234',
	'vexeniv': 'vexenx',
	'ayanosredscarf': 'ezichqog',
	'penquin': 'privatepenquin',
	'mraldo': 'mraldopls',
	'sawsbuck': 'deerling',
	'litten': 'samurott',
	'samurott': 'litten',
	'lunala': 'lunalavioleif',
	'wishes': 'unfixable',
	'nerd': 'eee4444444',
	'blaziken': 'knmfksdnf',
	'andy': 'agkoemv',
	'kris': 'likj9ajz', // THIRD color change >:|
	'nv': 'larvitar',
	'iyarito': '8f40n',
	'paris': 'goojna',
	'moo': 'soccerzxii',
	'lyren': 'solarisfaux',
	'tiksi': 'tikse',
	'ev': 'eeveegeneral',
	'chespin': 'd4ukzezn',
	'halite': 'rosasite',
	'thankyou': 'o5t9w5jl',
	'wally': 'wallythebully',
	'ant': 'nui',
	'nui': 'ant',
	'centiskorch': 'l99jh',
	'ceteris': 'eprtiuly',
	'om': 'omroom',
	'roman': 'wt2sd0qh',
	'maroon': 'rucbwbeg',
	'lyd': 'ahdjfidnf',
	'perry': 'mrperry',
	'yogibears': 'bwahahahahahahahaha',
	'tjay': 'teej19',
	'explodingdaisies': '85kgt',
	'flare': 'nsyncluvr67',
	'tenshi': 'tenshinagae',
	'pre': '0km',
	'ransei': '54j7o',
	'snaquaza': 'prrrrrrrrr',
	'alpha': 'alphawittem',
	'asheviere': '54hw4',
	'taranteeeno': 'moondazingo',
	'rage': 'hipfiregod',
	'andrew': 'stevensnype',
	'robyn': 'jediruwu',
	'birdy': 'cmstrall',
	'pirateprincess': '45mbh',
	'tempering': 'tempho',
	'chazm': 'chazmicsupanova',
	'arsenal': '558ru',
	'buffy': 'cvpux4zn',
	'luigi': 'luifi',
	'mitsuki': 'latiosred',
	'faku': 'ifaku',
	'pablo': 'arrested',
	'facu': 'facundoooooooo',
	'gimmick': 'gimm1ck',
	'pichus': 'up1gat8f',
	'pigeons': 'pigeonsvgc',
	'clefable': '147x0', // +HiMyNamesL, former gstaff - apparently cleared with Zarel via Discord PM
	'splash': 'mitsukokongou',
	'talah': '2b',
	'vexen': 'vexeniv',
	'shuutsukiyama': 'spankmepikachu',
	'blaz': 'blazask',
	'annika': 'l07kxym4',
	'tuthur': 'tuthur1',
	'moutemoute': 'fjlelzmzp',
	'mia': 'whgmpdku',
	// alt of mia
	'elisabetsobeck': '2sr28lp1',
	'inactive': 'xfd6bys3',
	'trace': 'mashirokurata',
	'celine': 'celine13',
	'hydro': '683tdwj6',
	'pants': 'stnap',
	'zap': 'zapcolor5',
	'avarice': 'ava823',
	'finch': 'finchinator',
	'tpp': 'teampokepals',
	'zarif': 'zariftest103',
	'milak': 'rasbhari',
	'dya': 'dyaaaaaaa',
	'instruct': 'vgc24',
	'jayi': 'prank',
	'pujo': 'ballombre',
	'blah': 'shubashubashub',
	'sfg': 'saltyfrenchguy',
	'sectonia': '6gv44c3w',
	'awa': 'awanderingcaelum',
	'vani': '6an2khng',
	'duel': 'duelmex',
	'lily': 'lilburr',
	'ara': 'phoenixara',
	'sakito': 'bysakito',
	'dnb': 'onlyrandomstuff',
	'niko': 'nikogoh',
	'ophion': 'ophi0n',
	'dflo': 'dragonflo',
	'cleffa': 'momopono',
	'skies': 'skiesjfk',
	'empo': 'gsz9pvp6',
	'devin': 'devwin',
	'keys': 'dream',
	'think': 'thinkerino',
	'rosa': 'glyx',
	'king': 'kingswordyt',
	'ltg': 'loltrollgame',
	'peary': 'hreybb',
	'alex': '17ot7i28',
	'zalm': 'vk0hw40x',
	'swiffix': 'a7ms4bok',
	'partman': '9tjak2hz',
	'monkey': 'henka',
	'soulwind': 'malahuju',
	'eris': 'marjane',
	'theia': 'nolnerd',
	'litwick': 'nolnerd',
	'grimm': 'grimmnightmare',
	'violet': 'fi4li3t3',
	'avery': 'ayvery',
	'altthiel': 'rqj7oxwm',
	'tranquilityy': 'axgwd',
	'micoy': 'micoy21',
	'pyro': 'loschunkos',
	'clementine': '45xlimv0',
	'boat': 'phiwings99',
	'isaiah': 'menacing',
	'ruby': 'woooooooooooooooo',
	'kaede': 'kaedy',
	'senko': 'emillight',
	'towelie': 'alore',
	'hisuianzoroark': 'supervillainx',
	'mochi': 'bocchihitori',
	'mex': 'megaeeveex',
	'eli': '75hr8qhl',
	'k': 'kennedy',
	'importo': 'fcportoisthebest',
	'rsb': 'rustysheriffbadge',
	'rumia': 'akumajou',
	'enrique': 'j3f2gdsz',
	'kolohe2': 'sundrops',
	'santiago': 'sevt',
	'jakee': 'jayyke',
	'pikachusean': 'ple8chwn',
	'tranquility': 'axgwd',
	'syrinix': 'blunix',
	'talonflame': 'ut',
	'neko': 'alotofnekos',
	'siegfried': 'meistersiegfried',
	'roxie': 'roxiee',
	'aigis': 'narukami',
	'mimejr': 'h9o4q4jg',
	'beauts': 'platinna',
	'ducky': 'mudkipbowl',
	'zee': 'zeefable',
	'sulo': 'suloxiv',
	'shiloh': 'oic9lxkq',
	'cathy': '' //{color: '#ff5cb6'}
};

// `defaultserver` specifies the server to use when the domain name in the
// address bar is `Config.routes.client`.
Config.defaultserver = {
	id: 'showdown',
	host: 'sim3.psim.us',
	port: 443,
	httpport: 8000,
	altport: 80,
	registered: true
};

/*** Begin automatically generated configuration ***/
Config.version = "0.11.2 (9f348ab4)";

Config.routes = {
	root: 'pokemonshowdown.com',
	client: 'play.pokemonshowdown.com',
	dex: 'dex.pokemonshowdown.com',
	replays: 'replay.pokemonshowdown.com',
	users: 'pokemonshowdown.com/users',
};
/*** End automatically generated configuration ***/


exports.Config = Config;