name: Node.js CI

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'LICENSE'
        - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
        - 'LICENSE'
        - 'README.md'

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
