name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
